# distroless instead of scratch for tls support
FROM gcr.io/distroless/static-debian12:nonroot AS final
ARG TARGETPLATFORM

WORKDIR /app

COPY $TARGETPLATFORM/traefik-opnsense-sync ./

ENTRYPOINT ["./traefik-opnsense-sync"]
